<?php

declare(strict_types=1);

use Infrangible\CatalogProductCustomerBenefit\Block\Product\View\Options\Type\CustomerBenefit;
use Magento\Framework\Escaper;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var CustomerBenefit $block */
/** @var Escaper $escaper */
?>

<?php
$option = $block->getOption();
$class = $option->getIsRequire() ? ' required' : '';
$dataSelector = 'options[' . $option->getId() . ']';
$price = $option->getPrice();
?>
<div class="field<?= /* @noEscape */ $class ?>">
    <label class="label" for="select_<?= $escaper->escapeHtmlAttr($option->getId()); ?>">
        <span><?= $escaper->escapeHtml($option->getTitle()); ?></span>
    </label>
    <div class="control">
        <div class="field choice admin__field admin__field-option">
            <input type="checkbox"
                   class="checkbox admin__control-checkbox <?= $option->getIsRequire() ? 'required': ''; ?> product-custom-option"
                   name="options[<?= $escaper->escapeHtmlAttr($option->getId()); ?>]"
                   id="options_<?= $escaper->escapeHtmlAttr($option->getId()); ?>"
                   value="1"
                   data-selector="<?= $escaper->escapeHtmlAttr($dataSelector); ?>"
                   price="<?= $escaper->escapeHtmlAttr($block->getCurrencyByStore($price)); ?>"
            />
            <label class="label admin__field-label"
                   for="options_<?= $escaper->escapeHtmlAttr($option->getId()); ?>">
                <span>
                    <?= $escaper->escapeHtml($option->getTitle()); ?>
                </span>
                <?= /* @noEscape */ $block->formatPrice($price); ?>
            </label>
        </div>
        <?php if ($option->getIsRequire()): ?>
            <?php if ($option->getType() == 'benefit_checkbox'): ?>
                <span id="options-<?= $escaper->escapeHtmlAttr($option->getId()); ?>-container"></span>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
