<?php

declare(strict_types=1);

use Infrangible\CatalogProductCustomerBenefit\Block\Adminhtml\Product\Edit\Tab\Options\Type\CustomerBenefit;
use Magento\Framework\Escaper;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var CustomerBenefit $block */
/** @var Escaper $escaper */
?>

<script id="custom-option-benefit-type-template" type="text/x-magento-template">
    <div id="product_option_<%- data.option_id %>_type_<%- data.group %>" class="fieldset">
        <table class="data-table">
            <thead>
                <tr class="headings">
                    <th class="col-sku"><?= $escaper->escapeHtml(__('SKU')); ?></th>
                    <th class="col-frontend"><?= $escaper->escapeHtml(__('Frontend')); ?></th>
                    <th class="col-label"><?= $escaper->escapeHtml(__('Label')); ?></th>
                </tr>
            </thead>
            <tr>
                <td>
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][sku]"
                           class="input-text type-sku"
                           value="<%- data.sku %>"
                           type="text">
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][frontend]"
                           class="input-text type-frontend"
                           value="<%- data.frontend %>"
                           type="checkbox">
                    <!--suppress HtmlFormInputWithoutLabel -->
                    <input name="product[options][<%- data.option_id %>][label]"
                           class="input-text type-label"
                           value="<%- data.label %>"
                           type="text">
                </td>
            </tr>
        </table>
    </div>
</script>
